#!/usr/bin/env python
# coding: utf-8

"""
Species Abundance Query Script
This script helps identify the abundance of certain species at certain times
from the CSV files generated by figure_comparison.py
"""

import pandas as pd
import numpy as np
import os
import sys
from pathlib import Path

def str_to_array(s):
    """Convert string of comma-separated values to numpy array"""
    return np.array([float(x) for x in s.split(',')])

def load_csv_files(fig_dir):
    """
    Load all CSV statistics files from a figure directory.
    
    Returns:
        dict: Dictionary with keys like 'label1', 'label2', etc. and values as DataFrames
    """
    csv_files = {}
    
    # Find all CSV files that match the pattern *_species_statistics.csv
    for csv_file in Path(fig_dir).glob('*_species_statistics.csv'):
        # Extract label from filename (everything before _species_statistics.csv)
        label = csv_file.stem.replace('_species_statistics', '')
        csv_files[label] = pd.read_csv(csv_file)
        print(f"Loaded CSV for '{label}': {csv_file.name}")
    
    return csv_files

def find_species(df, pattern, case_sensitive=False):
    """
    Find species matching a pattern in the DataFrame.
    
    Args:
        df: DataFrame with 'Species' column
        pattern: String pattern to search for (supports partial matching)
        case_sensitive: Whether search should be case sensitive
    
    Returns:
        List of matching species names
    """
    if case_sensitive:
        matches = df[df['Species'].str.contains(pattern, na=False)]['Species'].tolist()
    else:
        matches = df[df['Species'].str.contains(pattern, case=False, na=False)]['Species'].tolist()
    return matches

def get_abundance_at_time(df, species_name, time_point, tolerance=0.1):
    """
    Get abundance values for a species at a specific time point.
    
    Args:
        df: DataFrame with species statistics
        species_name: Name of the species (exact match)
        time_point: Target time point in minutes
        tolerance: Time tolerance for finding closest time point
    
    Returns:
        dict: Dictionary with 'time', 'average', 'min', 'max', 'exact_time'
    """
    # Find the species row
    species_row = df[df['Species'] == species_name]
    
    if len(species_row) == 0:
        return None
    
    row = species_row.iloc[0]
    
    # Parse time and abundance arrays
    times = str_to_array(row['Time'])
    averages = str_to_array(row['Average'])
    mins = str_to_array(row['Min'])
    maxs = str_to_array(row['Max'])
    
    # Find closest time point
    time_diffs = np.abs(times - time_point)
    closest_idx = np.argmin(time_diffs)
    closest_time = times[closest_idx]
    
    # Check if within tolerance
    if abs(closest_time - time_point) > tolerance:
        print(f"Warning: Closest time point is {closest_time:.2f} min (requested {time_point:.2f} min)")
    
    return {
        'species': species_name,
        'requested_time': time_point,
        'exact_time': closest_time,
        'average': averages[closest_idx],
        'min': mins[closest_idx],
        'max': maxs[closest_idx],
        'time_index': closest_idx
    }

def query_species_abundance(csv_files, species_pattern, time_points, tolerance=0.1):
    """
    Query abundance for species matching a pattern at specific time points.
    
    Args:
        csv_files: Dictionary of label -> DataFrame
        species_pattern: Pattern to match species names
        time_points: List of time points to query
        tolerance: Time tolerance for finding closest time point
    
    Returns:
        dict: Nested dictionary with results [label][species][time]
    """
    results = {}
    
    for label, df in csv_files.items():
        results[label] = {}
        
        # Find matching species
        matching_species = find_species(df, species_pattern)
        
        if not matching_species:
            print(f"No species found matching '{species_pattern}' in {label}")
            continue
        
        for species in matching_species:
            results[label][species] = {}
            
            for time_point in time_points:
                abundance = get_abundance_at_time(df, species, time_point, tolerance)
                if abundance:
                    results[label][species][time_point] = abundance
    
    return results

def print_abundance_table(results):
    """Print a formatted table of abundance results"""
    if not results:
        print("No results to display")
        return
    
    # Collect all unique species and time points
    all_species = set()
    all_times = set()
    for label_data in results.values():
        for species in label_data.keys():
            all_species.add(species)
            for time in label_data[species].keys():
                all_times.add(time)
    
    all_species = sorted(all_species)
    all_times = sorted(all_times)
    
    # Print table for each species
    for species in all_species:
        print(f"\n{'='*80}")
        print(f"Species: {species}")
        print(f"{'='*80}")
        print(f"{'Dataset':<20} {'Time (min)':<12} {'Average':<15} {'Min':<15} {'Max':<15}")
        print("-" * 80)
        
        for label in sorted(results.keys()):
            if species in results[label]:
                for time in all_times:
                    if time in results[label][species]:
                        data = results[label][species][time]
                        print(f"{label:<20} {data['exact_time']:<12.2f} "
                              f"{data['average']:<15.2f} {data['min']:<15.2f} {data['max']:<15.2f}")

def interactive_query(csv_files):
    """Interactive mode for querying species abundance"""
    print("\n" + "="*80)
    print("Species Abundance Query Tool")
    print("="*80)
    
    while True:
        print("\nOptions:")
        print("1. Search for species by pattern")
        print("2. Query abundance at specific time(s)")
        print("3. List all available species")
        print("4. Compare species across datasets at specific time")
        print("5. Export results to CSV")
        print("6. Exit")
        
        choice = input("\nEnter your choice (1-6): ").strip()
        
        if choice == '1':
            pattern = input("Enter species pattern to search: ").strip()
            print(f"\nSearching for species matching '{pattern}'...")
            
            for label, df in csv_files.items():
                matches = find_species(df, pattern)
                if matches:
                    print(f"\n{label}:")
                    for i, species in enumerate(matches, 1):
                        print(f"  {i}. {species}")
                else:
                    print(f"\n{label}: No matches found")
        
        elif choice == '2':
            species_pattern = input("Enter species pattern (or exact name): ").strip()
            time_input = input("Enter time point(s) in minutes (comma-separated): ").strip()
            
            try:
                time_points = [float(t.strip()) for t in time_input.split(',')]
            except ValueError:
                print("Invalid time format. Please use comma-separated numbers.")
                continue
            
            # Find matching species
            all_matches = []
            for label, df in csv_files.items():
                matches = find_species(df, species_pattern)
                all_matches.extend([(label, sp) for sp in matches])
            
            if not all_matches:
                print(f"No species found matching '{species_pattern}'")
                continue
            
            # Query abundance
            results = {}
            for label, df in csv_files.items():
                matches = find_species(df, species_pattern)
                if matches:
                    results[label] = {}
                    for species in matches:
                        results[label][species] = {}
                        for time_point in time_points:
                            abundance = get_abundance_at_time(df, species, time_point)
                            if abundance:
                                results[label][species][time_point] = abundance
            
            print_abundance_table(results)
        
        elif choice == '3':
            print("\nAvailable species:")
            all_species = set()
            for label, df in csv_files.items():
                species_list = df['Species'].unique()
                all_species.update(species_list)
                print(f"\n{label} ({len(species_list)} species):")
                for i, species in enumerate(sorted(species_list), 1):
                    print(f"  {i:3d}. {species}")
                    if i >= 50:  # Limit display
                        print(f"  ... and {len(species_list) - 50} more")
                        break
        
        elif choice == '4':
            species_pattern = input("Enter species pattern (or exact name): ").strip()
            time_input = input("Enter time point in minutes: ").strip()
            
            try:
                time_point = float(time_input)
            except ValueError:
                print("Invalid time format.")
                continue
            
            # Query and display comparison
            print(f"\n{'='*80}")
            print(f"Comparison at t = {time_point} min")
            print(f"{'='*80}")
            print(f"{'Dataset':<20} {'Species':<30} {'Average':<15} {'Min':<15} {'Max':<15}")
            print("-" * 80)
            
            for label, df in csv_files.items():
                matches = find_species(df, species_pattern)
                for species in matches:
                    abundance = get_abundance_at_time(df, species, time_point)
                    if abundance:
                        print(f"{label:<20} {species:<30} "
                              f"{abundance['average']:<15.2f} "
                              f"{abundance['min']:<15.2f} "
                              f"{abundance['max']:<15.2f}")
        
        elif choice == '5':
            species_pattern = input("Enter species pattern (or exact name): ").strip()
            time_input = input("Enter time point(s) in minutes (comma-separated): ").strip()
            
            try:
                time_points = [float(t.strip()) for t in time_input.split(',')]
            except ValueError:
                print("Invalid time format.")
                continue
            
            # Query abundance
            results = {}
            for label, df in csv_files.items():
                matches = find_species(df, species_pattern)
                if matches:
                    results[label] = {}
                    for species in matches:
                        results[label][species] = {}
                        for time_point in time_points:
                            abundance = get_abundance_at_time(df, species, time_point)
                            if abundance:
                                results[label][species][time_point] = abundance
            
            # Convert to DataFrame for export
            export_data = []
            for label, label_data in results.items():
                for species, species_data in label_data.items():
                    for time_point, abundance in species_data.items():
                        export_data.append({
                            'Dataset': label,
                            'Species': species,
                            'Time_min': abundance['exact_time'],
                            'Average': abundance['average'],
                            'Min': abundance['min'],
                            'Max': abundance['max']
                        })
            
            if export_data:
                export_df = pd.DataFrame(export_data)
                output_file = input("Enter output filename (default: species_abundance_export.csv): ").strip()
                if not output_file:
                    output_file = "species_abundance_export.csv"
                
                export_df.to_csv(output_file, index=False)
                print(f"\nResults exported to {output_file}")
                print(f"Total rows: {len(export_df)}")
            else:
                print("No data to export")
        
        elif choice == '6':
            print("Exiting...")
            break
        
        else:
            print("Invalid choice. Please enter 1-6.")

def main():
    """Main function"""
    if len(sys.argv) > 1:
        # Command-line mode
        fig_dir = sys.argv[1]
    else:
        # Interactive mode - ask for directory
        fig_dir = input("Enter path to trajectory_comparison directory: ").strip()
    
    if not os.path.exists(fig_dir):
        print(f"Error: Directory '{fig_dir}' does not exist")
        sys.exit(1)
    
    # Load CSV files
    print(f"\nLoading CSV files from: {fig_dir}")
    csv_files = load_csv_files(fig_dir)
    
    if not csv_files:
        print(f"No CSV files found in {fig_dir}")
        print("Looking for files matching pattern: *_species_statistics.csv")
        sys.exit(1)
    
    # Run interactive query
    interactive_query(csv_files)

if __name__ == "__main__":
    main()

